[package]
name = "xybt"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
elf = "0.6.1"
memmap = "0.7.0"
libc = "0.2.137"
auxv = "0.3.3"
numeric-enum-macro = "0.2.0"
